'use client'

import { useAuth } from '@/hooks/useAuth'
import { useRouter, useParams } from 'next/navigation'
import { useCallback, useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { CampaignWebflowPanel } from '@/components/campaigns/CampaignWebflowPanel'
import { CampaignVisualEditor } from '@/components/campaigns/CampaignVisualEditor'
import Link from 'next/link'

interface ContentAsset {
  id: string
  assetType: string
  content: string
  createdAt: string
}

interface Campaign {
  id: string
  name: string
  description?: string
  industry: string
  targetAudience: string
  goals: string[]
  status: string
  renderedHtml?: string | null
  webflowCmsItemId?: string | null
  template?: { id: string; name: string } | null
  contentAssets: ContentAsset[]
}

export default function CampaignDetail() {
  const router = useRouter()
  const params = useParams()
  const orgId = params.orgId as string
  const campaignId = params.campaignId as string
  const { user, loading: authLoading } = useAuth()

  const [campaign, setCampaign] = useState<Campaign | null>(null)
  const [loading, setLoading] = useState(true)
  const [savingPage, setSavingPage] = useState(false)
  const [selectedTab, setSelectedTab] = useState('page')
  const [autoGenerateDone, setAutoGenerateDone] = useState(false)
  const [pageGenerating, setPageGenerating] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)

  const fetchCampaign = useCallback(async () => {
    const res = await fetch(`/api/campaigns/${campaignId}`)
    const data = await res.json()
    if (data.campaign) setCampaign(data.campaign)
  }, [campaignId])

  useEffect(() => {
    if (!authLoading && !user) {
      router.push('/auth/login')
    }
  }, [user, authLoading, router])

  useEffect(() => {
    if (!campaignId) return
    setLoading(true)
    fetchCampaign().finally(() => setLoading(false))
  }, [campaignId, fetchCampaign])

  useEffect(() => {
    if (loading || !campaign || autoGenerateDone) return
    if (typeof window === 'undefined') return
    const q = new URLSearchParams(window.location.search)
    if (q.get('generate') !== '1') return
    setAutoGenerateDone(true)
    setPageGenerating(true)
    setGenerateError(null)
    window.history.replaceState({}, '', `/dashboard/${orgId}/campaigns/${campaignId}`)
    fetch(`/api/campaigns/${campaignId}/generate-page`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ launchBrief: campaign.description }),
    })
      .then(async (r) => {
        const data = await r.json()
        if (!r.ok) throw new Error(data.error ?? 'Generation failed')
        if (data.html) setCampaign((prev) => (prev ? { ...prev, renderedHtml: data.html } : prev))
      })
      .catch((e) => {
        setGenerateError(e instanceof Error ? e.message : 'Generation failed')
      })
      .finally(() => setPageGenerating(false))
  }, [loading, campaign, autoGenerateDone, campaignId, orgId])

  const handleSavePage = async (html: string) => {
    setSavingPage(true)
    try {
      const res = await fetch(`/api/campaigns/${campaignId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ renderedHtml: html }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setCampaign(data.campaign)
    } finally {
      setSavingPage(false)
    }
  }

  const handleGeneratePage = async (launchBrief?: string) => {
    const res = await fetch(`/api/campaigns/${campaignId}/generate-page`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ launchBrief }),
    })
    const data = await res.json()
    if (!res.ok) throw new Error(data.error)
    setCampaign((prev) => (prev ? { ...prev, renderedHtml: data.html } : prev))
    return data.html as string
  }

  if (authLoading || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="size-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
      </div>
    )
  }

  if (!campaign) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">Campaign not found</h2>
          <Link href={`/dashboard/${orgId}`}>
            <Button>Back to Dashboard</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <div>
            <Link href={`/dashboard/${orgId}`}>
              <span className="text-muted-foreground hover:text-foreground cursor-pointer">
                ← Back
              </span>
            </Link>
            <h1 className="text-2xl font-bold mt-2">{campaign.name}</h1>
            <p className="text-muted-foreground">
              {campaign.industry} · {campaign.targetAudience}
            </p>
          </div>
          <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium">
            {campaign.status}
          </span>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="border-b mb-6">
          <div className="flex gap-6 flex-wrap">
            {[
              { id: 'page', label: 'Page editor' },
              { id: 'webflow', label: 'Webflow CMS' },
              { id: 'assets', label: `AI snippets (${campaign.contentAssets.length})` },
              { id: 'settings', label: 'Settings' },
            ].map((tab) => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setSelectedTab(tab.id)}
                className={`pb-3 font-medium border-b-2 transition-colors ${
                  selectedTab === tab.id
                    ? 'border-primary text-primary'
                    : 'border-transparent text-muted-foreground hover:text-foreground'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {selectedTab === 'page' && (
          <>
            {generateError ? (
              <p className="mb-4 text-sm text-destructive">{generateError}</p>
            ) : null}
            <CampaignVisualEditor
              html={campaign.renderedHtml ?? ''}
              launchBrief={campaign.description ?? ''}
              onSave={handleSavePage}
              onGenerate={handleGeneratePage}
              saving={savingPage}
              pageGenerating={pageGenerating}
            />
          </>
        )}

        {selectedTab === 'webflow' && (
          <CampaignWebflowPanel
            campaignId={campaignId}
            orgId={orgId}
            webflowCmsItemId={campaign.webflowCmsItemId}
            templateName={campaign.template?.name}
            campaignStatus={campaign.status}
          />
        )}

        {selectedTab === 'assets' && (
          <div className="text-sm text-muted-foreground space-y-4">
            <p>
              Optional AI snippets. Your Webflow page is built in the{' '}
              <button
                type="button"
                className="underline"
                onClick={() => setSelectedTab('page')}
              >
                Page editor
              </button>
              .
            </p>
            {campaign.contentAssets.length === 0 ? (
              <p>No extra assets yet.</p>
            ) : (
              <div className="grid gap-4 sm:grid-cols-2">
                {campaign.contentAssets.map((asset) => (
                  <div key={asset.id} className="rounded-lg border p-4 bg-card">
                    <h3 className="text-xs font-semibold uppercase text-primary mb-2">
                      {asset.assetType.replace(/_/g, ' ')}
                    </h3>
                    <p className="whitespace-pre-wrap text-sm">{asset.content}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {selectedTab === 'settings' && (
          <div className="rounded-lg border p-6 bg-card space-y-3 text-sm">
            <p>
              <span className="text-muted-foreground">Industry:</span> {campaign.industry}
            </p>
            <p>
              <span className="text-muted-foreground">Audience:</span> {campaign.targetAudience}
            </p>
            {campaign.goals.length > 0 && (
              <ul className="list-disc pl-5">
                {campaign.goals.map((g) => (
                  <li key={g}>{g}</li>
                ))}
              </ul>
            )}
          </div>
        )}
      </main>
    </div>
  )
}
